# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ed3adc249a340e634d94a6581c390aea19d1b0ea87243a7cefa2ae116bddeb7e3ca470e0c519ee4c941225ba33a6f7e0e6209cae94cf234ab2eb6566ce62c1d

test:
  secret_key_base: 90f61736f32876b0b0b3ee50d7d636f48881521b101cc8b48603751853565db4db9f4a5249386839eddb11c89c64384db33b8f47d38e37c7ba21b54112bc58f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
